INSERT INTO Countries VALUES ('Nigeria',1,0,NULL,GETDATE());

INSERT INTO States VALUES (1,'Abia',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Akwa-Ibom',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Anambra',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Bauchi',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Bayelsa',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Benue',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Borno',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Cross River',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Delta',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Ebonyi',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Edo',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Ekiti',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Enugu',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Gombe',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Imo',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Jigawa',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Kaduna',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Kano',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Katsina',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Kebbi',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Kogi',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Kwara',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Lagos',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Nasarawa',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Niger',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Ogun',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Ondo',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Osun',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Oyo',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Plateau',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Rivers',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Sokoto',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Taraba',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Yobe',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Zamfara',1,0,NULL,GETDATE());
INSERT INTO States VALUES (1,'Abuja',1,0,NULL,GETDATE());


INSERT INTO CommonDropdowns VALUES (1,'Female',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (1,'Male',1,0,NULL,GETDATE());

INSERT INTO CommonDropdowns VALUES (2,'Christianity',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (2,'Islamic',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (2,'Judaism',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (2,'Paganism',1,0,NULL,GETDATE());

INSERT INTO CommonDropdowns VALUES (4, 'Main',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (4, 'About',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (4, 'Event',1,0,NULL,GETDATE());

INSERT INTO CommonDropdowns VALUES (5, 'General',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (5, 'Lifestyle',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (5, 'Religion',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (5, 'Design',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (5, 'IT',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (5, 'Education',1,0,NULL,GETDATE());

INSERT INTO CommonDropdowns VALUES (6, 'Naira',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (6, 'Us Dollar',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (6, 'Euro',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (6, 'British Pound',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (6, 'Israeli Shekel',1,0,NULL,GETDATE());

INSERT INTO CommonDropdowns VALUES (7, 'Ministry Support',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (7, 'Project',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (7, 'Mission',1,0,NULL,GETDATE());
INSERT INTO CommonDropdowns VALUES (7, 'Registration',1,0,NULL,GETDATE());

